// Record ids: UUIDv7 (RFC 9562), generated by whoever creates the record (usually the
// client, so optimistic rows have their final id). Time-ordered, so sorting by id is
// sorting by creation time, which breaks order_key ties between concurrent inserts.

let lastMs = 0;
let seq = 0;

export function newId(now: number = Date.now()): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  // Keep ids from one generator strictly increasing within a millisecond: a 12-bit counter
  // in rand_a (RFC 9562 §6.2 method 1), seeded randomly each new millisecond.
  if (now <= lastMs) {
    now = lastMs;
    seq++;
    if (seq > 0xfff) {
      now = ++lastMs;
      seq = 0;
    }
  } else {
    lastMs = now;
    seq = ((bytes[6] ?? 0) & 0x07) << 8; // random start, leaving headroom
  }
  let ms = now;
  for (let i = 5; i >= 0; i--) {
    bytes[i] = ms & 0xff;
    ms = Math.floor(ms / 256);
  }
  bytes[6] = 0x70 | ((seq >> 8) & 0x0f);
  bytes[7] = seq & 0xff;
  bytes[8] = 0x80 | ((bytes[8] ?? 0) & 0x3f);
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Ids accepted from clients: any UUID/ULID-ish token. */
export function isValidId(id: unknown): id is string {
  return typeof id === "string" && /^[A-Za-z0-9_-]{8,64}$/.test(id);
}
