-- Default select options (docs/spec/data-model.md). Editable per show later.
INSERT INTO `field_options` (`table`, `field`, `value`, `color`, `position`) VALUES
  ('cues', 'status', 'Not started', 'gray', 0),
  ('cues', 'status', 'In process', 'yellow', 1),
  ('cues', 'status', 'Rendered', 'blue', 2),
  ('cues', 'status', 'Cued', 'green', 3),
  ('cues', 'trigger_type', 'Line', 'blue', 0),
  ('cues', 'trigger_type', 'LX', 'yellow', 1),
  ('cues', 'trigger_type', 'SQ', 'purple', 2),
  ('cues', 'trigger_type', 'Timecode', 'teal', 3),
  ('cues', 'trigger_type', 'Visual', 'pink', 4),
  ('cues', 'trigger_type', 'Follow', 'gray', 5),
  ('cues', 'trigger_type', 'Manual', 'orange', 6),
  ('content', 'status', 'Not started', 'gray', 0),
  ('content', 'status', 'In process', 'yellow', 1),
  ('content', 'status', 'Rendered', 'blue', 2),
  ('content', 'status', 'Delivered', 'green', 3),
  ('content', 'status', 'Cut', 'red', 4),
  ('notes', 'type', 'Content', 'blue', 0),
  ('notes', 'type', 'Programming', 'purple', 1),
  ('notes', 'type', 'Director', 'red', 2),
  ('notes', 'type', 'Prod Mtg', 'orange', 3),
  ('notes', 'type', 'Admin', 'gray', 4),
  ('notes', 'type', 'Technical', 'teal', 5),
  ('notes', 'type', 'Artistic', 'pink', 6),
  ('notes', 'type', 'R&D', 'yellow', 7),
  ('notes', 'type', 'Stage Management', 'green', 8),
  ('notes', 'status', 'Open', 'blue', 0),
  ('notes', 'status', 'In progress', 'yellow', 1),
  ('notes', 'status', 'Done', 'green', 2),
  ('notes', 'priority', '1', 'red', 0),
  ('notes', 'priority', '2', 'orange', 1),
  ('notes', 'priority', '3', 'yellow', 2),
  ('notes', 'priority', '4', 'blue', 3),
  ('notes', 'priority', '5', 'gray', 4),
  ('persons', 'group', 'Video team', 'purple', 0),
  ('persons', 'group', 'Production', 'blue', 1),
  ('persons', 'group', 'Creative', 'pink', 2),
  ('persons', 'group', 'Cast', 'orange', 3),
  ('persons', 'group', 'Crew', 'teal', 4),
  ('scenes', 'act', 'Preshow', 'gray', 0),
  ('scenes', 'act', 'Act 1', 'blue', 1),
  ('scenes', 'act', 'Intermission', 'gray', 2),
  ('scenes', 'act', 'Act 2', 'purple', 3),
  ('scenes', 'act', 'Postshow', 'gray', 4);
